AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  [Project Name] Frontend
  Single Page Application (SPA) hosted on S3 + CloudFront.

Parameters:
  AppEnv:
    Type: String
    Description: Deployment Environment (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev
  RepositoryName:
    Type: String
    Description: GitHub Repository Name (for tagging)
    Default: [Project Name]

Resources:
  # 1. S3 Bucket for React App
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "-hosting-"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref AppEnv

  # 2. CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # 3. CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: S3Origin
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          # SPA Routing: Fallback to index.html for non-asset 404s
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
      Tags:
        - Key: Environment
          Value: !Ref AppEnv

  # 4. Bucket Policy to allow CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront:::distribution/"

Outputs:
  WebsiteUrl:
    Description: "CloudFront URL"
    Value: !Sub "https://"
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref FrontendBucket
  DistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref FrontendDistribution
